# 服务器端口号
server:
  port: 8704  servlet:    encoding:      charset: UTF-8

spring:
  application:
    name: allen-hystrix-dashboard
  main:
    banner-mode: "off"

# 请求地址：http://localhost:8704/hystrix
        
      